name: Daily Commit

on:
  schedule:
    - cron: "0 4 * * *" # Every day at 4:00 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a commit
        run: |
          echo "🕒 Commit on $(date)" >> activity.md
          git config --global user.name "Nikhil Raj A"
          git config --global user.email "nikhilsiri2003@gmail.com"
          git add activity.md
          git commit -m "📅 Daily commit - $(date)" || echo "No changes to commit"
          git push
