name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing changes to repo

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: NikhilRaj-2003
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "🐍 update snake game"
          git push
